package mrobsidy.rockycore.misc;

public enum ChatFormats {
	DARK_RED, RED, GOLD, YELLOW, DARK_GREEN, GREEN, AQUA, DARK_AQUA, DARK_BLUE, BLUE,
	LIGHT_PURPLE, DARK_PURPLE, WHITE, GRAY, DARK_GRAY, BLACK, CMD_RESET, ITALIC, BOLD, 
	UNDERLINE, STRIKE, CMD_MAGICLETTERS
}
